on: [push]

jobs:
  test_get-version-key-from-json-action:
    runs-on: ubuntu-latest
    name: A job to test whether the get-version-key-from-json action is working
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version Key from JSON
        uses: ./ # Uses an action in the root directory
        id: get-version-key-from-json-step
        with:
          path-to-json : './test-data/package.json'
      - name: print version output
        run: echo "The version key in your json was ${{ steps.get-version-key-from-json-step.outputs.version }}"
     